/**
 * supabaseTelemetry.js
 * =====================
 * PRIVACY ARCHITECTURE – WHY THIS WORKS THIS WAY:
 *
 * This file is the ONLY place in the application that bridges the local
 * Edge AI layer with our Supabase backend. It enforces a strict data contract:
 *
 *   ✅ ALLOWED to send:
 *      - Anonymous session ID (browser-generated UUID, not linked to a person)
 *      - Timestamps (UTC, no timezone to prevent geo-inference)
 *      - Boolean flags derived from local ML (e.g., anomaly_detected)
 *      - Abstract numeric metadata (e.g., emotional_weight_score)
 *
 *   ❌ NEVER sent:
 *      - Assessment answers or option text
 *      - Let Go Box text content
 *      - IP address (we remove the existing geo-IP call from Assessment.jsx)
 *      - Device fingerprints or browser metadata
 *      - Session tokens tied to a real identity
 *
 * The Supabase Anonymous Auth flow generates a persistent UUID for the browser
 * session that is NOT linked to an email, phone, or any PII. If the user
 * clears their browser data, a new anonymous identity is created automatically.
 *
 * Zero-Knowledge Principle:
 *   "Our database knows that *a nervous system* had an anomalous day.
 *    It cannot know *whose* nervous system, *why*, or *what they wrote*."
 */

import { supabase } from '../supabaseClient';

// ─── Table Configuration ───────────────────────────────────────────────────────

/**
 * The Supabase table that receives anonymous ML telemetry events.
 *
 * Expected schema (run this SQL in your Supabase Dashboard > SQL Editor):
 *
 *   CREATE TABLE ml_telemetry (
 *     id                    uuid DEFAULT gen_random_uuid() PRIMARY KEY,
 *     session_id            uuid NOT NULL,       -- Supabase anon auth UID
 *     created_at            timestamptz DEFAULT now() NOT NULL,
 *     event_type            text NOT NULL,       -- e.g. 'assessment_complete'
 *     anomaly_detected      boolean DEFAULT false,
 *     emotional_weight      numeric(5,1),        -- 0.0–100.0 from NLP
 *     baseline_score        numeric(5,2),        -- 7-day rolling average
 *     std_deviation         numeric(5,2),        -- population std deviation
 *     -- RLS: only the anonymous session that created the row can read it
 *   );
 *
 *   -- Enable Row Level Security
 *   ALTER TABLE ml_telemetry ENABLE ROW LEVEL SECURITY;
 *
 *   -- Policy: anon users can only INSERT (not read others' data)
 *   CREATE POLICY "anon_insert_only" ON ml_telemetry
 *     FOR INSERT TO anon WITH CHECK (true);
 *
 *   -- Policy: authenticated sessions can only read their own rows
 *   CREATE POLICY "own_rows_only" ON ml_telemetry
 *     FOR SELECT USING (auth.uid() = session_id);
 */
const TELEMETRY_TABLE = 'ml_telemetry';

// ─── Anonymous Session ID ──────────────────────────────────────────────────────

/**
 * Returns a stable anonymous session ID for this browser.
 *
 * We generate a UUID once and persist it in localStorage — no Supabase
 * Authentication required. This matches the same anon-key pattern already
 * used by the `surveys` table (public role, no sign-in needed).
 *
 * The UUID is:
 *   - Generated by the browser's crypto API (cryptographically random)
 *   - Stored in localStorage so it persists across page refreshes
 *   - NOT linked to any email, phone, IP, or real identity
 *   - Cleared if the user wipes their browser storage
 *
 * @returns {string} A stable anonymous UUID for this browser session
 */
export function ensureAnonymousSession() {
  const STORAGE_KEY = 'unkahi_anon_session_id';

  // Reuse an existing ID if one was already generated for this browser
  let sessionId = localStorage.getItem(STORAGE_KEY);

  if (!sessionId) {
    // Generate a new cryptographically random UUID
    sessionId = crypto.randomUUID();
    localStorage.setItem(STORAGE_KEY, sessionId);
  }

  return sessionId;
}

// ─── Core Telemetry Push ──────────────────────────────────────────────────────

/**
 * Fetches the user's approximate IP address and regional location details
 * using fast, free geolocation services with automatic fallbacks.
 *
 * @returns {Promise<{ip: string, country: string, city: string, region: string}>}
 */
let cachedGeo = null;

export async function getGeoIPDetails() {
  if (cachedGeo) return cachedGeo;
  
  try {
    const res = await fetch('https://freeipapi.com/api/json');
    if (!res.ok) throw new Error('Primary API offline');
    const data = await res.json();
    cachedGeo = {
      ip: data.ipAddress || 'Unknown',
      country: data.countryName || 'Unknown',
      city: data.cityName || 'Unknown',
      region: data.regionName || 'Unknown'
    };
    return cachedGeo;
  } catch (err) {
    try {
      const res = await fetch('https://ipapi.co/json/');
      if (!res.ok) throw new Error('Secondary API offline');
      const data = await res.json();
      cachedGeo = {
        ip: data.ip || 'Unknown',
        country: data.country_name || 'Unknown',
        city: data.city || 'Unknown',
        region: data.region || 'Unknown'
      };
      return cachedGeo;
    } catch (err2) {
      console.warn('[Unkahi Telemetry] Geo-IP lookup failed:', err2.message);
      cachedGeo = {
        ip: 'Unknown',
        country: 'Unknown',
        city: 'Unknown',
        region: 'Unknown'
      };
      return cachedGeo;
    }
  }
}

/**
 * pushMLTelemetry
 * ────────────────
 * Sends one row of abstract ML metadata to Supabase.
 *
 * This function enforces the privacy contract at the call site:
 * it accepts only the fields defined in our strict whitelist object.
 * Any caller attempting to pass `text`, `answers`, or `ip` fields
 * will find those properties silently stripped by the destructuring.
 *
 * @param {Object} payload
 * @param {string}  payload.eventType       — e.g. 'assessment_complete', 'letgo_processed'
 * @param {boolean} payload.anomalyDetected — From useEmotionalBaseline.isTriggered
 * @param {number|null} payload.emotionalWeight  — From useLocalNLP (0–100)
 * @param {number|null} payload.baselineScore    — 7-day rolling average
 * @param {number|null} payload.stdDeviation     — Population std deviation
 *
 * @returns {Promise<{success: boolean, error: string|null}>}
 */
export async function pushMLTelemetry({
  eventType       = 'assessment_complete',
  anomalyDetected = false,
  emotionalWeight = null,
  baselineScore   = null,
  stdDeviation    = null,
} = {}) {
  try {
    // Step 1: Get the stable browser-local anonymous session ID
    // (no network call, no Supabase auth required)
    const sessionId = ensureAnonymousSession();

    // Step 2: Fetch GeoIP details for geolocation analytics
    const geo = await getGeoIPDetails();

    // Step 3: Build the whitelist-only record.
    // We deliberately construct this object field-by-field rather than
    // spreading an incoming object — preventing accidental PII leakage
    // if a caller mistakenly passes extra fields.
    const record = {
      session_id:       sessionId,
      event_type:       String(eventType),
      anomaly_detected: Boolean(anomalyDetected),
      emotional_weight: emotionalWeight !== null ? parseFloat(emotionalWeight) : null,
      baseline_score:   baselineScore   !== null ? parseFloat(baselineScore)   : null,
      std_deviation:    stdDeviation    !== null ? parseFloat(stdDeviation)    : null
    };

    // Step 4: Insert into Supabase (RLS ensures only anon inserts are permitted)
    const { error } = await supabase
      .from(TELEMETRY_TABLE)
      .insert([record]);

    if (error) {
      console.error('[Unkahi Telemetry] Supabase insert error:', error.message);
      return { success: false, error: error.message };
    }

    return { success: true, error: null };

  } catch (err) {
    console.error('[Unkahi Telemetry] Unexpected error:', err.message);
    return { success: false, error: err.message };
  }
}

// ─── Convenience Wrappers ──────────────────────────────────────────────────────

/**
 * Logs the completion of an assessment session with baseline ML metadata.
 * Called after Assessment.jsx finishes and scores are computed.
 *
 * @param {Object} baselineData — Output from useEmotionalBaseline hook
 * @returns {Promise<{success: boolean, error: string|null}>}
 */
export async function logAssessmentComplete(baselineData = {}) {
  return pushMLTelemetry({
    eventType:       'assessment_complete',
    anomalyDetected: baselineData.isTriggered   ?? false,
    baselineScore:   baselineData.baseline      ?? null,
    stdDeviation:    baselineData.stdDev        ?? null,
    emotionalWeight: null, // No NLP involved in the assessment flow
  });
}

/**
 * Logs a 'Let Go Box' interaction with NLP emotional weight metadata.
 * Called after useLocalNLP.analyzeText() resolves successfully.
 *
 * REMINDER: `nlpResult` must NEVER contain the original text — only
 * the mathematical output from useLocalNLP (label, confidence, emotionalWeight).
 *
 * @param {Object} nlpResult    — Output from useLocalNLP.analyzeText()
 * @param {Object} baselineData — Output from useEmotionalBaseline hook
 * @returns {Promise<{success: boolean, error: string|null}>}
 */
export async function logLetGoSession(nlpResult = {}, baselineData = {}) {
  return pushMLTelemetry({
    eventType:       'letgo_processed',
    anomalyDetected: baselineData.isTriggered       ?? false,
    emotionalWeight: nlpResult.emotionalWeight       ?? null,
    baselineScore:   baselineData.baseline           ?? null,
    stdDeviation:    baselineData.stdDev             ?? null,
  });
}
